### ISSUE TITLE
Another solution to the splitting deck of cards with 'while' loop

### ISSUE THREAD

**Issue by anp2937** [susanBuck/e2-fall23#10]
Maybe not the totally correct but short:

```
while(count($cards) > 0) {
    $playerCards[] = array_pop($cards);
    $computerCards[] = array_pop($cards);
}
```

Works **ok** with even number of elements in array.

**Comment by susanBuck** [comment]
This is so simple and smart! Adding it to my list of examples. :-)

**Comment by richiecarey** [comment]
Another option ...

```PHP
while ($deck) {
    $player1[] = array_shift($deck);
    $player2[] = array_shift($deck);
}
```

... also assuming a $deck array with an even number of cards.

**Comment by anp2937** [comment]
@richiecarey, looks much cleaner without unnecessary  array **count** inside **if** condition. Nice

**Comment by MNT-348** [comment]
> ```
> while ($deck) {
>     $player1[] = array_shift($deck);
>     $player2[] = array_shift($deck);
> }
> ```
> 
> ... also assuming a $deck array with an even number of cards.

Just as an addition for anyone reading the code for understanding: you don't need to have an even number of cards per se (you will if you want to assort cards for P1 and P2 evenly as **your target condition**, which you'll have to keep track of and possibly set conditionals for).
 
```while ($deck)``` will stop evaluating as ```True``` once there's **no more** cards (i.e. elements) within ```$deck```. It will be an empty array that evaluates as ```False```, and since the ```while``` loop's performance condition is that it keeps going ```while ($deck is True)```...it stops.
If you have an uneven number of elements in ```$deck```, then Player 1 is just going to end up with 1 extra card on the last round.

**Comment by anp2937** [comment]
You are right. On the last run Player 1 receives extra card while Player 2 receives NULL instead of a card. And is this case we will need to add another function to search NULL elements inside the array and it will be more code to write.
That is why I decided to specify that it works for even numbers. 

```<?php
$deck = [1,2,3];

while ($deck) {
    $player1[] = array_shift($deck);
    $player2[] = array_shift($deck);
}

print_r($player1);
print_r($player2);

echo "<br>".gettype($player2[1]);
```

Results will look like:

```
Array ( [0] => 1 [1] => 3 ) Array ( [0] => 2 [1] => )
NULL
```
