### ISSUE TITLE
VSCode won't update

### ISSUE THREAD

**Issue by Abisg** [susanBuck/e2-fall23#11]
Hello,

I attempted to update VS Code multiple times, but it automatically reverts to the old version. Is there a way to fix this?

**Comment by susanBuck** [comment]
Hm, odd. 

Some questions to help troubleshoot this:
+ Are you on Mac or Windows?
+ What process are you using to update?
+ What version does it keep reverting to?

**Comment by Abisg** [comment]
- Mac
- Manage -> Restart to Update
- Version 1.82.2

**Comment by susanBuck** [comment]
What version of Mac OS are you running? (This info is found by clicking the Apple Icon top left and choosing _"About this Mac"_).

I ask because I found [this note](https://code.visualstudio.com/docs/supporting/FAQ#_can-i-run-vs-code-on-old-macos-versions):

> VS Code desktop version starting with 1.83 (September 2023) is deprecating support for macOS Mojave (version 10.14 and older). Starting with VS Code 1.86 (January 2024), we will stop updating VS Code on macOS Mojave (version 10.14 and older). You will need to upgrade to a newer macOS version to use later versions of VS Code. VS Code will no longer provide product updates or security fixes on macOS Mojave (versions 10.14 and older) and VS Code version 1.85 will be the last available release for macOS Mojave (10.14 and older). You can learn more about upgrading your macOS version at [support.apple.com](https://support.apple.com/en-us/HT201260).

If it's not an OS compatibility issue, [other Googling around suggests a uninstall and reinstall could resolve the issue...](https://stackoverflow.com/questions/65444894/visual-studio-code-keeps-reverting-to-old-update)

**Comment by Abisg** [comment]
I have Sonoma 14.0. So I should reinstall?

**Comment by susanBuck** [comment]
Yeah, try reinstalling. Hopefully that does the trick but if not let me know.

**Comment by Abisg** [comment]
Update: Re-installing VS Code worked! Thank you!

**Comment by susanBuck** [comment]
Excellent! Glad that sorted it out. : )
