### ISSUE TITLE
Issue with the course logistics video

### ISSUE THREAD

**Issue by goodguygg** [susanBuck/e2-fall23#2]
I am trying to access course logistics video using the link
https://www.youtube.com/embed/ooDf6s9pJvc?rel=0&showinfo=0
but it says:
Video unavailable
This video has been removed by the uploader

**Comment by susanBuck** [comment]
Hi @goodguygg -

The new URL is https://www.youtube.com/embed/w2pb2x93uPA?rel=0&showinfo=0

I did have to re-upload this video because of an issue. When you refresh the [Week 1 outline](https://hesweb.dev/e2/week/1) it should have the updated/correct URL linked.

If not or you have any further issues, let me know!
