### ISSUE TITLE
Help with sessions on P2

### ISSUE THREAD

**Issue by alilienfeld** [susanBuck/e2-fall23#20]
In P1 my game was guessing high-low for the next card in a deck. I represented the deck with an array of numbers 1-13 having 4 of each. I could use array_pop function to choose a card from the deck after shuffling the array. After picking the initial card I would array_pop again to pick the next card. After running evaluation of guess if the game was still going I set the chosen card to next card so that the next card picked would be the next to be evaluated against. The game keep going in a while loop until a guess is wrong so every time the guess was correct the player would get the card, the turn would change and the next card would become the card to guess against.

Attaching link to git: https://github.com/alilienfeld/e2/blob/main/p1/index.php

```php
if($player_guess == $correct_answer or $correct_answer == 'tie') { 
        if($player_turn == 'Player 1') {
            $player_1_wins[] = $chosen_card;
            $chosen_card = $next_card;
            $player_turn = 'Player 2';
        } else {  
            $player_2_wins[] = $chosen_card;
            $chosen_card = $next_card;       
            $player_turn = 'Player 1';
        }
```

With P2 using form submission I am using forms processing type c to process on process.php then redirect back to index.php with the results. When I redirect back to index the deck is complete again and newly shuffled because the page re-loads my code to setup a card for the player to guess against. I'm trying to figure out how to keep the removed cards out of the deck so that I can add functionality to count a players winning streak.

Link to most recent commit: https://github.com/alilienfeld/e2/blob/main/p2/index.php

I tried placing the setup logic in an if !isset statement

```php
if (!isset($_SESSION['results'])) {
$deck = [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13];
shuffle($deck);
$chosen_card = array_pop($deck);
$next_card = array_pop($deck);
session_start();
$_SESSION['pick'] = $chosen_card;
$_SESSION['next'] = $next_card;
}
```

I clear results later on the page after storing them
```php
if (isset($_SESSION['results'])) {
    $results = $_SESSION['results'];
    $drawn_card = $results['Drawn'];
    $next_draw = $results['Next'];
    $winner = $results['Winner'];
    $guess = $results['Guess'];
    $answer = $results['Answer'];
    
    $_SESSION['results'] = null;
}
```

The result is that at http://e2p2.hesclassali.me/index.php the next card is still pulled after the first one is picked hen the page reloads.

**Goal:** Figure out how to only have the code to create the deck and shuffle it run the first time the player hits the page. After I want the next draw card to become the drawn card.

**Comment by alilienfeld** [comment]
Submitting my project as is but if anyone has any thoughts on this I'd still love any advise.

**Comment by susanBuck** [comment]
Hi @alilienfeld - FYI Looking at your code and this question right now. Will reply shortly.

**Comment by susanBuck** [comment]
Apologies for the delay, had a zoom meeting with a classmate before I could finish typing up my reply. 

I played around with your code and it was actually a really interesting challenge because while most of the games we're making start once the form is first submitted, your game needed to start when the page is first loaded.

As a result, your game logic was split into two pages:

1. `index.php` to initialize the deck and pick cards
3. `process.php` to determine the outcome

To streamline things, I wanted to find a way to consolidate the game logic all to `process.php`, that way `index.php` just had to focus on outputting the form, results, etc.

To facilitate this, I added code to `index.php` that would determine if the game had not yet been initialized, and if it hadn't, it redirects to `process.php` where it can be initialized.  That code looks like this:

```php
// If we're just landing on the index page and cards have not yet been picked
// redirect the user to the process page where that can happen
if(!isset($_SESSION['current_card'])) {
    header('Location: process.php');
}
```

Then the following code is in `process.php` to set up the deck. You'll also notice it resets the deck when there are no longer enough cards to continue playing:

```php
// If deck does not exist OR there are not enough cards to play again - reset the deck
if(!isset($_SESSION['deck']) or count($_SESSION['deck']) < 2) {
    // I simplified the deck for development/debugging purposes so I could 
    // quickly play through the game and test the scenario when the deck is empty
    $deck = [1,2,3,4,5,6,7,8];
// Otherwise, use the existing deck which exists in the session
} else {
    $deck = $_SESSION['deck'];
}
```

The deck is stored in the session so it can be maintained each time the user plays.


## Full example
[Here is the final code I ended up with after experimenting with your game...](https://gist.github.com/susanBuck/049b06ce58947705627210cba91e6adc)

[And here is that code running on my server...](http://alilienfeld-p2.hesweb.xyz/)

## Reset feature
You’ll note I introduced a "Reset" link that links to a page `reset.php`. All that page does is clears all the session values and redirects the user back to the index:

```php
<?php

session_start();
session_unset();

header('Location: index.php');
```

I added this "feature" mostly as a debugging tool - In the process of getting things working, there was lots of session trial/error and I found it helpful to have a quick way to just reset the session to a blank slate. I decided to leave it in in the end because it seemed useful if a user was only part-way through the deck and they wanted to start over. 

## Misc. notes about my code compared to yours

I did rework some of the language output of the game, just because I found it helpful when wrapping my head around the logic. If you end up incorporating any of my code, feel free to disregard any of my language changes. :-)

I did not incorporate any of the "win streak" code, just to keep this example simple. 

I did some renaming of variables, session keys, etc. so they were more consistent.  For example, in your code, you had some things like this:

```php
$_SESSION['pick'] = $chosen_card;
```
```php
$drawn_card = $results['Drawn'];
```

Here the idea of the "chosen card" is identified by 4 different names: _"pick", "chosen_card", "drawn_card", "Drawn"_.

You'll note in my code that any variables that are set or extracted from a session share the exact same name as they key used in that session. This sort of consistency just makes the code easier to follow and less prone to mistakes as you try to remember all the different terminology you use. 

This latter point isn't a huge deal - how you wrote it works of course - I just wanted to make note of it to avoid confusion when you're looking through my code example.

I think those are all the notable points/differences. Let me know if you have any follow-up questions!

**Comment by alilienfeld** [comment]
This is amazing! Thanks so much!!! 

I agree with your point about renaming the variables and making them consistent. I confused myself into quite a few errors  while working on this. I'll take this feedback for refactoring this and for future work.
