### ISSUE TITLE
Composer pre-install error - Pending kernel upgrade

### ISSUE THREAD

**Issue by nolinanna** [susanBuck/e2-fall23#21]
I was following the instructions to install the extensions for Composer and encountered this error:

<img width="873" alt="Composer Error" src="https://github.com/susanBuck/e2-fall23/assets/101819040/ec043740-3742-44b2-928d-b6ec851d00d8">

Not sure what to do. I did restart VS code, but that didn't affect anything.

**Comment by madagaluna** [comment]
I got this mesage and reinstalled the pre-extensions and ended up creating a huge mess because I had two instances running.  I ended up going down a rabbit hole of delete/purge/kill.  Let this be a cautionary tale!  Wait until someone can explain why this happened (I'm curious, too) before proceeding.  RN I'm wondering if I have everything installed correctly, but it seems to be working.   For the future, though, I'd like to know why I received this message and what the appropriate way to proceed is.   Good luck.  I wish I could be more help.

**Comment by ShakRowB** [comment]
I clicked enter and it cleared (i.e. restarted).

**Comment by susanBuck** [comment]
When this message pops up, you can hit the "Enter" key to proceed.

Then on the next screen when it asks you which services to restart you can hit "Enter" again. 

That should complete the process. 


## Why this happens
When we run `apt-get install` to install the modules we need for Composer, it also checks for other updates needed on our system and in this instance it detected there was an update to the kernel (the core of the operating system). Updating the kernel requires restarting the server.

The server setup I used in the lecture video was slightly different, which is why I didn't see the message at the time of recording. Apologies for any confusion! 

@madagaluna Since everything is working as expected, you're probably fine, but I'll log into your server tomorrow (Monday) just to double check for you (I'm currently away from my work computer, so can't log in right now). Will report back tomorrow  :).

**Comment by susanBuck** [comment]
@madagaluna - Update: I just logged into your server and everything appears set up correctly 👍

**Comment by madagaluna** [comment]
@susanBuck - Thank you for checking my server and for the explanation.
