### ISSUE TITLE
404 error when setting up custom route

### ISSUE THREAD

**Issue by dpurser-dev** [susanBuck/e2-fall23#23]
Hi Susan,

Following along with the Week 10 lecture, I created the contact page for ZipFoods. To do so, I completed the following steps:

1. Add the new route to the array in the routes.php file
2. Add the new method to the AppController.php file
3. Create a new view using the naming convention "contact.blade.php"

Unfortunately, I get a 404 error when I go my new URL (http://e2zipfoods.dpurser.me/contact). This is unusual, since the homepage and even updating the homepage to include the current time, works fine.

In an effort to debug this, I followed just steps 1 and 2 to create a page called "Test" (http://e2zipfoods.dpurser.me/test), which is supposed to only return a string. However, this also returns the 404 error.

I have committed the updated code (with the error) to my GitHub repository here: https://github.com/dpurser-dev/e2/tree/main/zipfoods

Would you mind having a look and seeing where I went wrong?

Thank you!

**Comment by anp2937** [comment]
Hello @dpurser-dev,
have you checked discussion regarding similar 404 issue [here](https://github.com/susanBuck/e2-fall23/issues/22) ?
Might be the same issue (I did not check your code, it's just a guess).

Although, I also do not understand why the home (index) page still works in this framework when the vhost configured to the project root with no index file available. Can someone explain this in details?

**Comment by dpurser-dev** [comment]
Nice one @anp2937, that fixed it! Thank you

For reference, I was missing a few parameters in my configuration file, specifically:

I was missing the "index.html" part of this:

`index index.php index.html;`

and I was missing this entire section:

`location / {
try_files $uri $uri/ /index.php?$query_string;
}`

**Comment by susanBuck** [comment]
Apologies for not emphasizing this better. In reviewing the lecture and notes, I do highlight how framework-specific site configs need to point to the "public" directory, but I fail to emphasize the addition of this location config:

```
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
```

This additional config tells the server to first attempt to load a directory/file for the specified $uri if it exists. If it does not exist, then it will route the request to index.php, which as we know is responsible for "bootstrapping" the app, invoking the routing system, etc.

If you copy [the config from the notes on framework setup](https://hesweb.dev/e2/notes/php/frameworks/setup#web-server-setup), you'll have the right code, but if you copy and modify an existing server block already in your sites file from earlier in the semester, you won't. This is because our earlier apps did not use a routing system and therefor did not need that location config.

Definitely something I need to point out better in future semesters so making a note about this! Apologies again for the confusion. :)

**Comment by susanBuck** [comment]
Just an FYI I updated the framework setup notes to highlight the addition of the location config:
https://hesweb.dev/e2/notes/php/frameworks/setup#web-server-setup

**Comment by dpurser-dev** [comment]
Thanks for the additional explanation Susan, that's super helpful! 

I usually try to code-along with the lecture (without copying and pasting from the notes), so that would explain how I missed it.  The updated notes look great.
