### ISSUE TITLE
what is App object

### ISSUE THREAD

**Issue by anp2937** [susanBuck/e2-fall23#24]
Trying to understand what is happening in index.php file but still have some questions.
The main question - I cannot understand where the  **App** object come from:

```
# Define constants
define('DOC_ROOT', $_SERVER['DOCUMENT_ROOT'].'/../');

# Initialize Composer autoloading
require DOC_ROOT.'/vendor/autoload.php';

# Initialize App object
$app = new E2\App();

# Invoke router
echo $app->route();
``` 

As I can guess - **App** class created here _vendor/susanbuck/e2core/src/App.php_ . Is this true?
If yes, how exactly it comes to our index.php file. I do not see any autoload file that points to it.

**Comment by susanBuck** [comment]
Good question @anp2937 -

The following line in `index.php` brings in our autoloading information generated by Composer:

```php
require DOC_ROOT.'/vendor/autoload.php';
```

**Recall that the autoloading system in Composer makes it so that we can invoke classes within our code without having to explicitly require/import each class. That's why we don't see a require/import statement specifically for the E2\App class.** 

If we look at our `composer.json` config file, we see `susanbuck/e2core` (the core of the framework) is listed as as one of our dependencies (so far it's the only dependency):

```json
"require": {
    "susanbuck/e2core": "^0.1.0"
},
```

So when Composer is invoked in our project (on initial install or anytime we run `composer update`), it downloads the `susanbuck/e2core` software and puts it in the `vendor` directory. 

Then the code within the `DOC_ROOT.'/vendor/autoload.php';` file makes it so all the classes in the `vendor` directory are accessible within our application (without needing any additional require/import statements for those classes).

To better understand how this works behind the scenes, open the file `vendor/composer/autoload_psr4.php`. This file is generated by Composer based on your dependencies (and their subdependencies). There's a line in there that looks like this:

```
'E2\\' => array($vendorDir . '/susanbuck/e2core/src'),
```

That line is what maps the `E2` namespace to the `'/susanbuck/e2core/src'` directory.

As a result, if we invoke `$app = new E2\App();`, our application is able to find the `App` class.

**_Summary:_ We tell Composer what software we want to use. Composer downloads that software and generates code making it possible for us to invoke any of that software without having to explicitly require/import it in our code. This system is called autoloading.**

Let me know if that helps clarify things. Happy to elaborate further!

**Comment by anp2937** [comment]
Thanks @susanBuck.
`vendor/composer/autoload_psr4.php` - this was the file I was looking for. 
Now it makes sense.
