### ISSUE TITLE
Hard reset and some other clarification questions on the homework

### ISSUE THREAD

**Issue by madagaluna** [susanBuck/e2-fall23#33]
I finished the first exercise and then made a terrible mess of my database while working on the second exercise.  I want to go back a few commits but the git reset -- hard command didn't work in my terminal.   What is the best way to go back two commits?

While I'm here, I should clarify a few things;
Should all the reviews be listed or should we clear them so only the most recent review shows up?  I went for the later but I am thinking I may be able to invoke the "fresh" method to only have one show.
Should the new products be entered on a new form or on the review form?  
 I'm not sure how to get around the naming issue with 'new'.  

TIA!

Mary

**Comment by susanBuck** [comment]
Hi @madagaluna -

To revert your code base to the state it was in a previous commit, first identify the commit you want to go back to. One way to do this is to run this command:

```bash
> git log --oneline
```

From the output, the 7 digit numbers on the left of each commit is the unique hash for that commit. Make note of the hash of the commit you want to go back and run this command:

```bash
> git reset --hard <commit_hash>
```

Finally, run this command to push the reset to Github:

```bash
> git push -f
```

(*Note that the above approach will delete any of the commits made since the one you're reverting to. This is fine in the context which we're working, but if this were a "real world" project where you were collaborating with other developers, you'd want to be cautious with this approach - generally it's not a good idea to delete git history.*)

Going to reply to your second question in a separate reply.

**Comment by susanBuck** [comment]
> Should all the reviews be listed or should we clear them so only the most recent review shows up? I went for the later but I am thinking I may be able to invoke the "fresh" method to only have one show.

Show all the reviews that are currently in the database for the given product. 

In my example, invoking the "fresh" command clears all reviews then seeds 5 example reviews, distributed to product 1 and 2. 

> Should the new products be entered on a new form or on the review form?

You should create a new page/form for adding products.

> I'm not sure how to get around the naming issue with 'new'.

Not exactly sure what you mean by this? Let me know if it's still a pending question. : )

**Comment by madagaluna** [comment]
Thank you.  I ended up copying the code from the previous version.
